In [ ]:
#Install required packages (run this first in google colab)
!pip install numpy pandas matplotlib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import drive

import warnings
warnings.filterwarnings ('ignore')

print ("Numpy version:", np.__version__)
print ("Pandas version:", pd.__version__)

Numpy version: 2.1.3
Pandas version: 2.2.3


In [ ]:
#creating numpy array
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array ([[1, 2, 3], [4, 5, 6]])

print ("1D Array:", arr1)
print ("2D Array:\n",arr2)

print ("Array shape:", arr1.shape)
print ("Array dtype:", arr1.dtype)
print ("Array size:", arr1.size)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Array shape: (5,)
Array dtype: int64
Array size: 5


In [ ]:
#diffrent ways to create arrays
zeros_array = np.zeros ((3, 4), dtype =int)

ones_array =np.ones((2, 3))
range_array =np.arange(0, 10, 2)
linspace_array =np.linspace (0, 1, 5, dtype=int)

print ("zeros_array:\n", zeros_array)
print ("ones_array:\n", ones_array)
print ("range_array:\n", range_array)
print ("linspace array:\n", linspace_array)

zeros_array:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
ones_array:
 [[1. 1. 1.]
 [1. 1. 1.]]
range_array:
 [0 2 4 6 8]
linspace array:
 [0 0 0 0 1]


In [25]:
#math, statistics and broadcasting


#mathematical operations on arrays
a = np.array ([1, 2, 3, 4, 5])
b = np.array ([2, 3, 4, 5, 6])

#element wise operation
print ("Addition:", a + b)
print ("Multiplication:", a*b)
print ("Power:", a**2)
print ("Square root:", np.sqrt(a))

#statistical operation
print ("Mean:", np.mean(a))
print ("Standard deviation:", np.std(a))
print ("Min:", np.min(a))
print ("Max:", np.max(a))

#Broadcast example
matrix =np.array([[1, 2, 3], [4, 5, 6]])
vector =np.array([10, 20, 30])
result = matrix + vector
print ("Broadcasting result:\n", result)

Addition: [ 3  5  7  9 11]
Multiplication: [ 2  6 12 20 30]
Power: [ 1  4  9 16 25]
Square root: [1.         1.41421356 1.73205081 2.         2.23606798]
Mean: 3.0
Standard deviation: 1.4142135623730951
Min: 1
Max: 5
Broadcasting result:
 [[11 22 33]
 [14 25 36]]


In [27]:
#Index and slicing arrays

arr = np.array([10, 20, 30, 40, 50])
#Indexing
print ("Element at index 2:", arr[2])

#Slicing
print ("Sliced array (from index 1 to 3):", arr[1:4])

#2D slicing array
arr_2d =np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print ("Sliced 2D array (first two rows):\n", arr_2d[:2])

Element at index 2: 30
Sliced array (from index 1 to 3): [20 30 40]
Sliced 2D array (first two rows):
 [[1 2 3]
 [4 5 6]]
